### ISSUE TITLE
Improve installation description

### ISSUE THREAD

**Issue by giuliavezzani** [eleramp/RL_Easy21#1]
@eleramp 
I had some troubles in testing your code due this ambiguous step:

```
pip install -e gym-foo
```

Googling it, I found that actually the correct command for the installation in this case should be:

```
pip install -e gym-easy21/
```
This error might be due to my limited experience with `gym`, but I'd suggest to make things as easy as possible to the user.
Please update the [README.md](https://github.com/eleramp/RL_Easy21/blob/master/README.md). 
Also, providing the instructions for creating a [virtual environment](https://gist.github.com/Geoyi/d9fab4f609e9f75941946be45000632b#how-to-install-virtualenv) where to run your code is always a good practice: it makes things easier for the user. All the required dependencies can be collected in a `requirements.txt` file so that the user can install all of them just with the command:
```
 pip install -r requirements.txt
```

**Comment by eleramp** [comment]
> pip install -e gym-easy21/

Oh yes sorry!

Thanks for the suggestion, I'll do it!
